version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./base/base.json
  build-base:
    docker:
      - image: hashicorp/packer
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            apk --no-cache update
            apk --no-cache add python py-pip py-setuptools ca-certificates curl groff less jq
            pip --no-cache-dir install awscli
      - run:
          name: Build base
          command: ./scripts/build.sh base ./base/base.json
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - manifest-base.json
      - store_artifacts:
          path: manifest-base.json


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
